### ISSUE TITLE
点关机按钮，无法直接关机

### ISSUE THREAD

**Issue by itq5** [sakoula/XiaoMi-Air-6200U#11]
系统内选择关机，电源指示灯常量，未彻底关闭，望大神修复

**Comment by sakoula** [comment]
unfortunately this is a known bug and have not found a way to fix it yet.

**Comment by itq5** [comment]
可以试试这个。https://osx.cx/repair-dsdt.html

**Comment by sakoula** [comment]
Hi there, The fix you refer to is the old clover shutdown fix which does not work on the laptop (already tried that).

The idea behind the problem is that `_PTS` method called in `DSDT` when shutting down is not completely shutting off the machine. There are a number of fixes, tried many of them but unfortunately they do not work 👍 

* https://dortania.github.io/OpenCore-Post-Install/usb/misc/shutdown.html
* https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-RMCF.dsl
* https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-PTSWAK.dsl

In one experiment It seems that if you disable the trypeC port and USB3 shutdown is successful so it seems that it may be related with USB. Your best bet is to look around for other Skylate laptops and how they fixed that. 

Unfortunately I do not have the time to look at it more.

**Comment by whtiehack** [comment]
hi @sakoula 

as [this](http://bbs.pcbeta.com/viewthread-1847639-1-1.html) thread said, need disable left usb3.0 to resolve shutdown problem.

can you try it?

thanks for your awesome work.
